# Generated by Django 4.2.4 on 2024-11-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joined_products',
            field=models.ManyToManyField(related_name='users_joined', to='savings.savingsproducts'),
        ),
    ]
