# Generated by Django 4.2.4 on 2024-11-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
        ('accounts', '0002_user_joined_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joined_products',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_joined', to='savings.savingsproducts'),
        ),
    ]
