# Generated by Django 4.2.4 on 2024-11-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
        ('accounts', '0003_alter_user_joined_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='joined_products',
        ),
        migrations.AddField(
            model_name='user',
            name='subscribe_deposits',
            field=models.ManyToManyField(blank=True, null=True, to='savings.depositproducts'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribe_savings',
            field=models.ManyToManyField(blank=True, null=True, to='savings.savingsproducts'),
        ),
    ]
