# Generated by Django 4.2.4 on 2024-11-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
        ('accounts', '0005_alter_user_subscribe_deposits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscribe_deposits',
            field=models.ManyToManyField(blank=True, to='savings.depositproducts'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribe_savings',
            field=models.ManyToManyField(blank=True, to='savings.savingsproducts'),
        ),
    ]
