# Generated by Django 4.2.4 on 2024-11-22 03:18

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_subscribe_deposits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='annual_income',
            field=models.BigIntegerField(blank=True, help_text='연 소득(만원)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=accounts.models.user_profile_path, verbose_name='프로필 이미지'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_assets',
            field=models.BigIntegerField(blank=True, help_text='총 자산(만원)', null=True),
        ),
    ]
